name: tests-pics

on:
  pull_request:
    paths:
      - 'pages/pics/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm test -- -f pics/index.test
