name: tests-components

on:
  pull_requests:
    paths:
      - 'src/components/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm test -- -f components/
