name: collywobbles

on: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  flibbertigibbet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm test
      